let num1 = +prompt('перше число');
let num2 = +prompt('дргуе число');
let sum = num1 + num2;
let sub = num1 - num2;
let mul = num1 * num2;
let div = num1 / num2;
console.log(sum);
console.log(sub);
console.log(mul);
console.log(div);
